name: secret-listener-trufflehog
on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - ".github/labeler.yml"
      - ".github/workflows/pr-labeler.yml"
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: trufflehog filesystem scan
        uses: trufflesecurity/trufflehog@v3
        with:
          args: filesystem --no-update --json --fail --only-verified --exclude-paths .gitignore .
